version: '3.8'

services:
  app:
    build: .
    container_name: ironplug-app
    restart: always
    ports:
      - "8082:8082"
      - "5432:5432"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MAIL_USERNAME=hocabilgic80.c@gmail.com
      - MAIL_PASSWORD=qisw epcm fqjy wohz
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local 