version: '3.8'

services:
  app:
    build: .
    container_name: ironplug-app
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MAIL_USERNAME=hocabilgic80.c@gmail.com
      - MAIL_PASSWORD=qisw epcm fqjy wohz
    depends_on:
      - postgres
    networks:
      - ironplug-network

  postgres:
    image: postgres:14-alpine
    container_name: ironplug-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ironplug
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ironplug-network

volumes:
  postgres-data:
    driver: local

networks:
  ironplug-network:
    driver: bridge 