services:
  - type: web
    name: ironplug-app
    env: docker
    repo: https://github.com/hocabilgic/ironplug.git
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free # Plan tipini belirleyin (ücretsiz, starter, vs.)
    healthCheckPath: /actuator/health # Sağlık kontrolü endpoint'i varsa
    numInstances: 1 # İstenen instance sayısı
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: SERVER_PORT
        value: 10000
      # DB Bilgileri
      - key: DB_HOST
        value: dpg-d0o2u97diees739k3o10-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: ironlgupdb
      - key: DB_USERNAME
        value: ironlgupdb
      - key: DB_PASSWORD
        sync: false # Render UI'dan girilecek
      # Mail Bilgileri
      - key: MAIL_USERNAME
        value: hocabilgic80.c@gmail.com
      - key: MAIL_PASSWORD
        sync: false # Render UI'dan girilecek
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      # JWT Bilgileri
      - key: JWT_EXPIRATION_MS
        value: 8640000
      # Default host değeri
      - key: DB_HOST_DEFAULT
        value: dpg-d0o2u97diees739k3o10-a.oregon-postgres.render.com