services:
  - type: web
    name: ironplug-app
    env: docker
    repo: https://github.com/yourusername/ironpluga.git
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
    
  - type: pserv
    name: ironplug-postgres
    env: docker
    plan: standard
    repo: https://github.com/yourusername/ironpluga.git
    image: postgres:14-alpine
    branch: main
    envVars:
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: ironplug 