services:
  - type: web
    name: ironplug-app
    env: docker
    repo: https://github.com/yourusername/ironpluga.git
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
    
